version: '3'
services:
  prerender:
    image: ghcr.io/bybe-inc/prerender-alpine:latest
    build:
      context: .
    ports:
      - 3010:3000
    environment:
      - MEMORY_CACHE=0
      - CACHE_MAXSIZE=1000
      - CACHE_TTL=6000
